apiVersion: apps/v1
kind: Deployment
metadata:
  name: match-simulator
  namespace: matchsense
  labels:
    app: match-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: match-simulator
  template:
    metadata:
      labels:
        app: match-simulator
    spec:
      enableServiceLinks: false
      containers:
        - name: match-simulator
          image: ghcr.io/nhatminh06/match-simulator@sha256:0dc307cec0a917ab4f546884ea694423334dd87e59223dc60978b3707fe6e161
          ports:
            - containerPort: 8082
          env:
            - name: EVENT_API_URL
              value: "http://event-api:8080"
            - name: MATCH_ID
              value: "ars-mci-2026"
            - name: HOME_TEAM
              value: "Arsenal"
            - name: AWAY_TEAM
              value: "Manchester City"
            - name: SPEED
              value: "2"
            - name: HEALTH_PORT
              value: "8082"
          resources:
            requests:
              memory: "16Mi"
              cpu: "25m"
            limits:
              memory: "32Mi"
              cpu: "50m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: 3
            periodSeconds: 5
