apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-processor
  namespace: matchsense
  labels:
    app: event-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-processor
  template:
    metadata:
      labels:
        app: event-processor
    spec:
      enableServiceLinks: false
      containers:
        - name: event-processor
          image: ghcr.io/nhatminh06/event-processor@sha256:1cebfbbd3910e38dedc9cc55f77542859653d21d857ce140d623e21cdac3a15b
          env:
            - name: KAFKA_BROKER
              value: "kafka:29092"
            - name: REDIS_URL
              value: "redis:6379"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "jaeger:4318"
          resources:
            requests:
              memory: "32Mi"
              cpu: "25m"
            limits:
              memory: "64Mi"
              cpu: "100m"