apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-redis
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nhatminh06/matchsense.git
    targetRevision: HEAD
    path: gitops/infrastructure/redis
  destination:
    server: https://kubernetes.default.svc
    namespace: matchsense
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
