apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-api
  namespace: matchsense
  labels:
    app: query-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query-api
  template:
    metadata:
      labels:
        app: query-api
    spec:
      enableServiceLinks: false
      containers:
        - name: query-api
          image: ghcr.io/nhatminh06/query-api@sha256:c2f058030fa614663c9337211de90ea7feedf0e6e28131330ea9aca1f38bd419
          ports:
            - containerPort: 8083
          env:
            - name: PORT
              value: "8083"
            - name: REDIS_URL
              value: "redis:6379"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "jaeger:4318"
          resources:
            requests:
              memory: "32Mi"
              cpu: "25m"
            limits:
              memory: "64Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8083
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8083
            initialDelaySeconds: 3
            periodSeconds: 5